server:
  servlet:
    context-path: /shopbridge
  port: ${PORT:9010}
spring:
  datasource:
    url: jdbc:h2:~/shopbridge
    driverClassName: org.h2.Driver
    username: shopbridge
    password: shopbridge@12345
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
